language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build
  - cargo test --all
  - cd trie-db && cargo check --no-default-features
  - cd ../memory-db && cargo check --no-default-features
